# Generated by Django 3.1.2 on 2020-10-27 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Not Available', 'Not Available'), ('Available', 'Available')], max_length=200, null=True),
        ),
    ]
